// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20250426132700_ajustseedfixDATAo")]
    partial class ajustseedfixDATAo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<int>("Cargo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome_completo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Nome_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_usuario");

                    b.Property<int>("Permissoes")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CPF = "00000000000",
                            Cargo = 1,
                            CreatedAt = new DateTime(2025, 4, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@exemplo.com",
                            Nome_completo = "Super Admin",
                            Nome_usuario = "superadmin",
                            Permissoes = 63,
                            Senha = "$2a$06$qzBEXhEPIkjOSHZcY1u6Cu7gJ88U9.8tGtyS5g1RfKpqg4AWbsk6i",
                            UpdatedAt = new DateTime(2025, 4, 25, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CPF = "11111111111",
                            Cargo = 3,
                            CreatedAt = new DateTime(2025, 4, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "usuario@exemplo.com",
                            Nome_completo = "Usuário Comum",
                            Nome_usuario = "usuario",
                            Permissoes = 8,
                            Senha = "$2a$06$qzBEXhEPIkjOSHZcY1u6Cu7gJ88U9.8tGtyS5g1RfKpqg4AWbsk6i",
                            UpdatedAt = new DateTime(2025, 4, 25, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
