// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20250426132145_ajustseedfixauto")]
    partial class ajustseedfixauto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<int>("Cargo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome_completo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Nome_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_usuario");

                    b.Property<int>("Permissoes")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bca7073-6a9e-4825-a218-59635e787148"),
                            CPF = "00000000000",
                            Cargo = 1,
                            CreatedAt = new DateTime(2025, 4, 26, 10, 21, 45, 613, DateTimeKind.Unspecified).AddTicks(4864),
                            Email = "superadmin@exemplo.com",
                            Nome_completo = "Super Admin",
                            Nome_usuario = "superadmin",
                            Permissoes = 63,
                            Senha = "$2a$06$qzBEXhEPIkjOSHZcY1u6Cu7gJ88U9.8tGtyS5g1RfKpqg4AWbsk6i",
                            UpdatedAt = new DateTime(2025, 4, 26, 10, 21, 45, 614, DateTimeKind.Unspecified).AddTicks(8969)
                        },
                        new
                        {
                            Id = new Guid("457f82ef-d838-48ec-8234-fa9df6249f0c"),
                            CPF = "11111111111",
                            Cargo = 3,
                            CreatedAt = new DateTime(2025, 4, 26, 10, 21, 45, 615, DateTimeKind.Unspecified).AddTicks(88),
                            Email = "usuario@exemplo.com",
                            Nome_completo = "Usuário Comum",
                            Nome_usuario = "usuario",
                            Permissoes = 8,
                            Senha = "$2a$06$qzBEXhEPIkjOSHZcY1u6Cu7gJ88U9.8tGtyS5g1RfKpqg4AWbsk6i",
                            UpdatedAt = new DateTime(2025, 4, 26, 10, 21, 45, 615, DateTimeKind.Unspecified).AddTicks(95)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
